classDiagram
  class ProviderAdapter
  <<interface>> ProviderAdapter

  class SearchService
  class BookingService
  class PaymentService
  class IssueService
  class RefundService

  class PaymentGatewayClient
  class NotifyClient

  ProviderAdapter : +search()
  ProviderAdapter : +review()
  ProviderAdapter : +issue()
  ProviderAdapter : +refund()

  SearchService ..> ProviderAdapter : "جست‌وجو"
  BookingService ..> ProviderAdapter : "بازبینی/صدور"
  IssueService ..> ProviderAdapter : "صدور"
  RefundService ..> ProviderAdapter : "استرداد"

  PaymentService ..> PaymentGatewayClient : "پرداخت/verify"
  IssueService ..> NotifyClient : "اعلان"
  RefundService ..> PaymentGatewayClient : "بازپرداخت"

