flowchart LR
  U[کاربر]
  UI[رابط وب/موبایل]
  API[سامانه سمت سرور]

  subgraph Ext[سرویس‌های بیرونی]
    P[تأمین‌کنندگان]
    PG[درگاه پرداخت]
    N[سرویس اعلان]
    S[سامانه پشتیبانی]
  end

  U --> UI --> API
  API --> P
  API --> PG
  API --> N
  API --> S

