flowchart TB
  U[کاربر]
  SP[تیم پشتیبانی]

  UC1((جست‌وجوی خدمات سفر))
  UC2((خرید بلیت))
  UC3((استرداد/لغو))
  UC4((شارژ کیف‌پول))
  UC5((ثبت تیکت پشتیبانی))

  U --> UC1
  U --> UC2
  U --> UC3
  U --> UC4
  U --> UC5
  SP --> UC5

