stateDiagram-v2
  [*] --> ایجاد_شد
  ایجاد_شد --> در_انتظار_پرداخت: ثبت سفارش
  در_انتظار_پرداخت --> لغو_شد: انصراف/انقضا
  در_انتظار_پرداخت --> پرداخت_تأیید_شد: راستی‌آزمایی موفق
  در_انتظار_پرداخت --> نیازمند_بررسی: راستی‌آزمایی مبهم
  نیازمند_بررسی --> پرداخت_تأیید_شد: تأیید دستی/اصلاح
  پرداخت_تأیید_شد --> در_حال_صدور: شروع صدور
  در_حال_صدور --> صدور_انجام_شد: موفق
  در_حال_صدور --> صدور_ناموفق: شکست موقت/دائم
  صدور_ناموفق --> در_حال_صدور: تلاش‌مجدد
  صدور_ناموفق --> نیازمند_بررسی: ارجاع به پشتیبانی
  صدور_انجام_شد --> [*]
  لغو_شد --> [*]

